- name: nginx
  hosts: all
  vars:
    app: nginx
  tasks:
  - import_tasks: ../shared/prepare_docker_compose_app.yml

  - name: Copy static resources
    ansible.posix.synchronize:
      src: '../../privacy/out/'
      dest: '{{ target }}/'

  - name: "Allow http"
    become: true
    community.general.ufw:
      rule: allow
      port: http

  - name: "Allow https"
    become: true
    community.general.ufw:
      rule: allow
      port: https

  - name: "Allow ssh"
    become: true
    community.general.ufw:
      rule: allow
      port: ssh

  - name: "Allow local network traffic"
    become: true
    community.general.ufw:
      rule: allow
      to_ip: 172.17.0.1

  - name: "Enable firewall"
    become: true
    community.general.ufw:
      state: enabled

  - import_tasks: ../shared/restart_docker_compose_app.yml