- name: nginx
  hosts: all
  vars:
    app: nginx
  tasks:
  - import_tasks: ../shared/prepare_docker_compose_app.yml

  - name: Copy static resources
    ansible.builtin.copy:
      src: '../../privacy/out/'
      dest: '{{ target }}/'

  - name: "Allow http"
    become: true
    community.general.ufw:
      rule: allow
      port: http

  - name: "Allow https"
    become: true
    community.general.ufw:
      rule: allow
      port: https

  - name: "Enable firewall"
    become: true
    community.general.ufw:
      state: enabled

  - import_tasks: ../shared/restart_docker_compose_app.yml