- name: Docker
  hosts: all
  become: true
  vars:
    primary_user: jq
  tasks:
  - name: Install required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: "Enable docker"
    ansible.builtin.service:
      name: docker
      state: started
      enabled: true

  - name: Add primary user to docker group
    ansible.builtin.user:
      name: '{{ primary_user }}'
      append: true
      groups: 'docker'
