- name: Firewall
  hosts: all
  tasks:

  - name: "Allow http"
    become: true
    community.general.ufw:
      rule: allow
      port: http

  - name: "Allow https"
    become: true
    community.general.ufw:
      rule: allow
      port: https

  - name: "Allow OpenSSH"
    become: true
    community.general.ufw:
      rule: allow
      name: OpenSSH

  - name: "Allow local network traffic"
    become: true
    community.general.ufw:
      rule: allow
      to_ip: 172.17.0.1

  # - name: "Enable firewall"
  #   become: true
  #   community.general.ufw:
  #     state: enabled