- name: Reboot
  hosts: all
  become: yes
  tasks:
  - name: "Add scheduled daily reboot near morning"
    ansible.builtin.cron:
      name: daily reboot
      hour: '05'
      minute: '00'
      job: shutdown -r