- name: Stop App
  community.docker.docker_compose_v2:
    state: absent
    project_src: '{{ target }}'

- name: Pull App
  register: docker_pull_app
  community.docker.docker_compose_v2:
    pull: always
    project_src: '{{ target }}'

- name: Restart App
  community.docker.docker_compose_v2:
    state: restarted
    project_src: '{{ target }}'

- name: Restart NGinx
  community.docker.docker_compose_v2:
    state: restarted
    project_src: '{{ nginx_app_directory }}'