version: "3"

services:
  feedragon:
    image: ghcr.io/johannes-qvarford/feedragon:master
    container_name: feedragon
    ports:
      - "9999:8080"
    restart: unless-stopped
    volumes:
      - ./feedragon.toml:/feedragon.toml