version: "3"

services:
  feedragon:
    image: ghcr.io/johannes-qvarford/feedragon:master
    ports:
      - "9999:8080"
    environment:
      DB_CONNECTION_STRING: postgres://postgres:password@db/app
    restart: unless-stopped
    volumes:
      - ./feedragon.toml:/feedragon.toml
  db:
    image: postgres:14
    ports:
      - "9998:5432"
    environment:
      POSTGRES_PASSWORD: password
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - "9997:8080"
    restart: unless-stopped