- name: Nitter
  hosts: all
  vars:
    app: nitter
  tasks:
  - import_tasks: ../shared/prepare_docker_compose_app.yml
  
  - name: Copy Nitter configuration file
    ansible.builtin.copy:
      src: nitter_app.conf
      dest: '{{ target }}/'

  - import_tasks: ../shared/restart_docker_compose_app.yml