- name: Home
  hosts: all
  vars:
    app: home
  tasks:
  - name: Copy NGinx file
    ansible.builtin.copy:
      src: '{{ app }}.conf'
      dest: '{{ nginx_sites_enabled_directory }}/'
      
  - name: Copy static resources
    ansible.posix.synchronize:
      src: '../../privacy/out/'
      dest: '{{ nginx_app_directory }}/out/'

  - name: Restart NGinx
    community.docker.docker_compose:
      state: present
      restarted: true
      pull: true
      project_src: '{{ nginx_app_directory }}'