- name: Libreddit
  hosts: all
  vars:
    target: '{{ apps_directory }}/libreddit'
  tasks:
  # - name: Ping my hosts
  #   ansible.builtin.ping:
  # - name: Print message
  #   ansible.builtin.debug:
  #     msg: Hello world
  # - name: Debug command
  #   become: yes
  #   become_user: root
  #   command: pwd
  #   register: debug
  # - debug: var=debug
  - name: Create directory if not already exists
    file:
      path: '{{ target }}'
      state: directory

  - name: Copy Docker-Compose file
    ansible.builtin.copy:
      src: docker-compose.yml
      dest: '{{ target }}/'

  - name: Copy NGinx file
    ansible.builtin.copy:
      src: libreddit.conf
      dest: '{{ nginx_sites_enabled_directory }}/'

  - name: Restart App
    community.docker.docker_compose:
      state: present
      restarted: true
      pull: true
      project_src: '{{ target }}'

  - name: Restart NGinx
    community.docker.docker_compose:
      state: present
      restarted: true
      pull: true
      project_src: '{{ nginx_app_directory }}'